sudo: required
language: android
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.3
  - android-22
  - android-28
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-28
  - add-on
  - extra
  - sys-img-armeabi-v7a-android-22
  licenses:
  - android-sdk-preview-license-52d11cd2
  - android-sdk-license-.+
  - google-gdk-license-.+
script:
- "./gradlew assembleDebug"
after_script:
- "./gradlew crashlyticsUploadDistributionDebug"
before_script:
- echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
- emulator -avd test -no-skin -no-audio -no-window &
- android-wait-for-emulator
- adb shell input keyevent 82 &
before_install:
- chmod +x gradlew
- yes | sdkmanager "platforms;android-22"
before_deploy:
# Set up git user name and tag this commit
- git config --local user.name "AleksandrAleksandrov"
- git config --local user.email "aleksandraleksandrovua@gmail.com"
- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  api_key:
    secure: "j3dciIRBjQtuWH7chp3CetCR1hpKM7bopiFQSZ7njK8FFDs+HoGxhS+JOLNiwRtxD8PWI9Kv9IxVvd1xroBlpCPieZ05Db0hu0jGn/jkqRjLpWIVe7mB/fOAJHdgyWR+M5XgyHdDyycFfSgzgJmqh4ch7pP9qePTxhrUi6rYw6Tdnt5UpkkKYdITgV6pirh+ZiMLp8g0x9N8kvFsDOCgr8A7NCMvCyVqHUtHiENs209IdpQmRV9AAXVnCW7yKViGojkIHY/SExWt+jzZSD2Ud0pqwtTw5mrg+VP57nCdENId23C1hQVzXhmwK1Ybydm2p55Ek+3LS+Hmoj7d8m5Mt7Ythh5IxeIdKlf15c6MLcgetnjaNvZUnwETnkZskrGq8ttfQF6GsF+8Eb1Y1vaGQUYDkbaLom1Vad5DLsmCszx8gzkEGAV1TN+aD9uoXbcXVI16DML4Wyyx5PF7lHeqNrPVov9GeWvEkt5EEEVyJ1Fq8i/USInoLOJRRC9DvXybup82JMrvO3F1pE9tmSxhNCH7AopQEoTv85KKCarTnPR/iAIbqBnjle1kaOe1bkZ7uerPiZb53sg5LhvEk8vB/TrhD8mCh8OSRQIzbm83x38XGbxjHAxeXADkeKZjUCzLTaSfJ2BiQ8TSUfILcVBDdez1NODyqREmxOq5d2wvp98="
  file: "app/build/outputs/apk/*/**.apk"
  skip_cleanup: "true"
  file_glob: "true"
  skip_cleanup: true
  on:
    branch: master
    repo: AleksandrAleksandrov/Reminder
